# Generated by Django 4.1.7 on 2023-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meta',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=None, max_length=20, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
