# Generated by Django 4.1.7 on 2023-03-23 07:11

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Контент')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField()),
            ],
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='studentmeta',
            name='code',
        ),
        migrations.RemoveField(
            model_name='studentmeta',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentmeta',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentmeta',
            name='second_name',
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='asda', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ParentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.studentmeta')),
            ],
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='school',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.news'),
            preserve_default=False,
        ),
    ]
