# Generated by Django 4.1.7 on 2023-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_news_teachermeta_remove_studentmeta_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmeta',
            name='code',
            field=models.CharField(default=None, max_length=20, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentmeta',
            name='first_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentmeta',
            name='last_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentmeta',
            name='second_name',
            field=models.CharField(default='', max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmeta',
            name='code',
            field=models.CharField(default=None, max_length=20, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmeta',
            name='first_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmeta',
            name='last_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmeta',
            name='second_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermeta',
            name='code',
            field=models.CharField(default=None, max_length=20, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermeta',
            name='first_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermeta',
            name='last_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermeta',
            name='second_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentmeta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmeta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachermeta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
