# Generated by Django 4.1.7 on 2023-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_school_students_school_email_school_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='events',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='schedule',
            field=models.JSONField(null=True),
        ),
    ]
