# Generated by Django 4.1.7 on 2023-03-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_school_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.school'),
            preserve_default=False,
        ),
    ]
