# Generated by Django 4.1.7 on 2023-03-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_studentmeta_grade_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='parentmeta',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmeta',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermeta',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.school'),
            preserve_default=False,
        ),
    ]
